### ISSUE TITLE
Add short description to CONSTANTS section

### ISSUE THREAD

**Issue by asb-capfan** [PerlGameDev/AntTweakBar#1]
There is a section in the AntTweakBar POD listing some constants. 
What are they good for? 
If writing it in the POD would be redundant because it's written somewhere else, please provide a link to the other documentation. I personally would prefer the description in the POD. It reduces the amount of browser tabs when coding.

**Comment by basiliscos** [comment]
Thanks for reporting.

It isn't documented perfectly at the original library (http://anttweakbar.sourceforge.net/doc/tools:anttweakbar:twinit#parameters), but I have googled a bit and added an short description https://metacpan.org/pod/release/DMOL/AntTweakBar-0.02/lib/AntTweakBar.pm#CONSTANTS .
